#
# Copyright (c) 2020 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Set OpenThread NCP architecture
CONFIG_OPENTHREAD_COPROCESSOR=y
CONFIG_OPENTHREAD_COPROCESSOR_RCP=y
CONFIG_OPENTHREAD_THREAD_VERSION_1_2=y

# Activation du CSL et de la synchro vus dans ta capture
CONFIG_OPENTHREAD_CSL_RECEIVER=y
CONFIG_OPENTHREAD_CSL_AUTO_SYNC=y

# Souvent requis par OTBR pour Thread 1.2
CONFIG_OPENTHREAD_LINK_METRICS_SUBJECT=y

# Increase logging thread stack size due to Spinel backend needs
# CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048

# Enable OpenThread features set
CONFIG_OPENTHREAD_NORDIC_LIBRARY_MASTER=y

CONFIG_NET_L2_OPENTHREAD=y

# Generic networking options
CONFIG_NETWORKING=y

CONFIG_MBEDTLS_SHA1_C=n
CONFIG_FPU=y

CONFIG_IEEE802154=y
